name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v3

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with: 
            dotnet-version: 7.0.x
            
        - name: Install dependencies
          run: dotnet workload restore

        # Generate the website
        - name: Publish
          run: |
            cp wwwroot/index.html wwwroot/404.html
            dotnet publish blazorwasm.csproj --configuration Release
        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: bin/Release/net7.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            # cname: nakigoe.org
